spring:
  application:
    name: menu
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/backgammon
  #    driver-class-name: org.postgresql.Driver
  #    username: postgres
  #    password: admin

server:
  port: 81

cfg:
  start-game-id: 1

route:
  config:
    backgammon-game:
      #      host: ${GAME_HOST:http://localhost:82}
      uri: 'http://game-service:82'