spring:
  application:
    name: menu
  datasource:
    url: jdbc:postgresql://postgres-service:5432/menu
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


server:
  port: 81

cfg:
  start-game-id: 1

route:
  config:
    backgammon-game:
      #      host: ${GAME_HOST:http://localhost:82}
      uri: 'http://game-service:82'

disable-job: false