spring:
  application:
    name: backgammon-game
  data:
    mongodb:
      host: mongo-service
#      host: localhost
      port: 27017
      database: gammon-move

server:
  error:
    include-message: always
  port: 82
  servlet:
    context-path: /game

config:
  sse:
    time-out: ${GAME_SSE_TIMEOUT:#{100000000}}

  game:
    after-close-delay: 120

  jedis:
    host: redis-service
    port: 6379

debug: false
