spring:
  application:
    name: backgammon-game
  data:
    mongodb:
      host: mongo-service
#      host: localhost
      port: 27017
      database: gammon-move
    redis:
      host: ${config.jedis.host}
      port: ${config.jedis.port}
  cache:
    type: redis
    redis:
      time-to-live: 2m
  cloud:
    openfeign:
      client:
        config:
          engine:
            url: "http://game-engine:80"
            read-timeout: 30_000



  # spring.cache.redis.time-to-live=600000
  # spring.cache.redis.cache-null-values=false

server:
  error:
    include-message: always
  port: 82
  servlet:
    context-path: /game

config:
  sse:
    time-out: ${GAME_SSE_TIMEOUT:#{100000000}}

  game:
    after-close-delay: 120

  jedis:
    host: redis-service
    port: 6379

debug: false
