server:
  port: 80
  address: 0.0.0.0
spring:
  application:
    name: gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/backgammon
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
jwt:
  secret:
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  expire:
    1000000000000

route:
  token:
    name: 'token'
  header:
    auth-user:
      name: 'auth-user'

  config:
    menu:
      id: 'menu'
      path: 'menu/**'
      host: 'http://localhost:81'

    backgammon-game:
      id: 'backgammon-game'
      path: 'game/backgammon/**'
      host: 'http://localhost:82'


