server:
  port: 80
  address: 0.0.0.0

spring:
  application:
    name: gateway

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true


  datasource:

    url: jdbc:postgresql://postgres-service:5432/backgammon
#    url: jdbc:postgresql://${PLAYER_DB:localhost:5432/backgammon}
    driver-class-name: org.postgresql.Driver
#    username: ${PLAYER_DB_USER:postgres}
    username: postgres
#    password: ${PLAYER_DB_PASS:admin}
    password: admin

  data:
    jdbc:
      dialect: postgresql
jwt:
  secret: ${JWT_SECRET:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
  expire: ${PLAYER_TOKEN_EXPIRATION_TIME:100000}

route:
  token:
    name: 'token'
  header:
    auth-user:
      name: 'auth-user'

  config:
    menu:
      id: 'menu'
      path: 'menu/**'
#      host: ${MENU_HOST:http://localhost:81}
      host: 'http://menu-service:81'

    backgammon-game:
      id: 'backgammon-game'
      path: 'game/backgammon/**'
#      host: ${GAME_HOST:http://localhost:82}
      host: 'http://game-service:82'

