apiVersion: v1
kind: PersistentVolume
metadata:
  name: player-svc-pv
  labels:
    type: local
    app: narde-player
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/player-img

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: player-service-pvc
  labels:
    app: narde-player
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: narde-player
  labels:
    app: narde-player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: narde-player
  template:
    metadata:
      labels:
        app: narde-player
    spec:
      containers:
        - name: player-service
          image: narde-player:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 84
          envFrom:
            - configMapRef:
                name: narde-config
          volumeMounts:
            - mountPath: /var/image-data
              name: imagedata
      volumes:
        - name: imagedata
          persistentVolumeClaim:
            claimName: player-service-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: player-service
spec:
  ports:
    - port: 84
      targetPort: 84
  selector:
    app: narde-player
  type: ClusterIP

