apiVersion: apps/v1
kind: Deployment
metadata:
  name: narde-gateway
  labels:
    app: narde-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: narde-gateway
  template:
    metadata:
      labels:
        app: narde-gateway
    spec:
      containers:
        - name: gateway
          image: 176.108.249.125:5000/narde-gateway:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: narde-config
            - secretRef:
                name: narde-secret

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: narde-gateway
spec:
  selector:
    app: narde-gateway
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30003
  type: NodePort
